# Generated by Django 5.0.14 on 2026-09-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_placeholder', models.CharField(max_length=255)),
                ('strength_score', models.IntegerField(default=0)),
                ('strength_label', models.CharField(blank=True, max_length=20, null=True)),
                ('length', models.IntegerField(default=0)),
                ('has_uppercase', models.BooleanField(default=False)),
                ('has_lowercase', models.BooleanField(default=False)),
                ('has_numbers', models.BooleanField(default=False)),
                ('has_special', models.BooleanField(default=False)),
                ('character_count', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('link_speed', models.CharField(blank=True, max_length=30, null=True)),
                ('estimated_crack_time', models.CharField(blank=True, max_length=60, null=True)),
                ('is_common', models.BooleanField(default=False)),
                ('breached_count', models.IntegerField(default=0)),
                ('entropy', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('analysis_notes', models.TextField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analyzed_passwords',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommonPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=64, unique=True)),
                ('password_plaintext', models.CharField(blank=True, max_length=255, null=True)),
                ('appearance_rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'common_passwords',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('security_question', models.CharField(blank=True, max_length=255, null=True)),
                ('security_answer_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(default='full', max_length=50)),
                ('report_format', models.CharField(default='html', max_length=10)),
                ('total_analyses', models.IntegerField(default=0)),
                ('avg_strength', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weak_passwords', models.IntegerField(default=0)),
                ('medium_passwords', models.IntegerField(default=0)),
                ('strong_passwords', models.IntegerField(default=0)),
                ('common_detected', models.IntegerField(default=0)),
                ('recommendations_count', models.IntegerField(default=0)),
                ('report_data', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analyzer.user')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='analyzer.analyzedpassword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='analyzer.user')),
            ],
            options={
                'db_table': 'recommendations',
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.user')),
            ],
            options={
                'db_table': 'login_attempts',
            },
        ),
        migrations.AddField(
            model_name='analyzedpassword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyzer.user'),
        ),
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer.user')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_targets', to='analyzer.user')),
            ],
            options={
                'db_table': 'admin_activity_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
